from enum import StrEnum


class EvidenceTier(StrEnum):
    E0 = "E0"
    E1 = "E1"
    E2 = "E2"
    E3 = "E3"
    E4 = "E4"


class EvidenceStance(StrEnum):
    SUPPORTS = "SUPPORTS"
    REFUTES = "REFUTES"
    CONTEXT = "CONTEXT"
    NO_EVIDENCE = "NO_EVIDENCE"


class SourceRole(StrEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"


class ClaimSupportStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    CONTESTED = "CONTESTED"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class ResearchBriefStatus(StrEnum):
    VERIFIED = "VERIFIED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INSUFFICIENT = "INSUFFICIENT"
    REVIEWED = "REVIEWED"


class ConfidenceClass(StrEnum):
    C0 = "C0"
    C1 = "C1"
    C2 = "C2"
    C3 = "C3"
    C4 = "C4"


class RiskClass(StrEnum):
    R0 = "R0"
    R1 = "R1"
    R2 = "R2"
    R3 = "R3"


class WorkflowStatus(StrEnum):
    INGESTED = "INGESTED"
    CANDIDATE = "CANDIDATE"
    TOPIC_APPROVED = "TOPIC_APPROVED"
    VERIFIED = "VERIFIED"
    DRAFTED = "DRAFTED"
    ASSETS_READY = "ASSETS_READY"
    QA_PASSED = "QA_PASSED"
    EDITORIAL_APPROVED = "EDITORIAL_APPROVED"
    READY_TO_PUBLISH = "READY_TO_PUBLISH"
    PUBLISH_APPROVED = "PUBLISH_APPROVED"
    PUBLISHED = "PUBLISHED"
    DISTRIBUTED = "DISTRIBUTED"
    MEASURED = "MEASURED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class WorkflowActionType(StrEnum):
    TOPIC_PROPOSED = "TOPIC_PROPOSED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    DRAFT_COMPLETED = "DRAFT_COMPLETED"
    ASSETS_COMPLETED = "ASSETS_COMPLETED"
    QA_PASSED = "QA_PASSED"
    QA_REVISION_REQUIRED = "QA_REVISION_REQUIRED"
    PACKAGE_READY = "PACKAGE_READY"
    PUBLICATION_COMPLETED = "PUBLICATION_COMPLETED"
    DISTRIBUTION_COMPLETED = "DISTRIBUTION_COMPLETED"
    MEASUREMENT_CAPTURED = "MEASUREMENT_CAPTURED"
    GATE_DECIDED = "GATE_DECIDED"
    FAILURE_RETRYABLE = "FAILURE_RETRYABLE"
    FAILURE_TERMINAL = "FAILURE_TERMINAL"
    RETRY = "RETRY"
    BLOCK = "BLOCK"
    RESUME = "RESUME"


class TopicDecision(StrEnum):
    IGNORE = "IGNORE"
    WATCH = "WATCH"
    PROPOSE = "PROPOSE"


class TopicUrgency(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    BREAKING = "BREAKING"


class GateKind(StrEnum):
    TOPIC = "A"
    EDITORIAL = "B"
    PUBLISH = "C"


class GateOutcome(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    WATCH = "WATCH"


class AssetKind(StrEnum):
    IMAGE = "IMAGE"
    INFOGRAPHIC = "INFOGRAPHIC"
    VIDEO = "VIDEO"
    DOCUMENT = "DOCUMENT"
    OTHER = "OTHER"


class AssetOrigin(StrEnum):
    GENERATED = "GENERATED"
    EXTERNAL = "EXTERNAL"
    PROVIDED = "PROVIDED"


class AssetRightsStatus(StrEnum):
    CLEAR = "CLEAR"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    RESTRICTED = "RESTRICTED"


class AssetManifestStatus(StrEnum):
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class QAOutcome(StrEnum):
    PASS = "PASS"
    REVISE = "REVISE"
    BLOCK = "BLOCK"


class QAFindingSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    BLOCKER = "BLOCKER"


class PublicationStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class DistributionStatus(StrEnum):
    PREVIEW = "PREVIEW"
    DISPATCHING = "DISPATCHING"
    SCHEDULED = "SCHEDULED"
    POSTED = "POSTED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class AuditActorKind(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class SourceKind(StrEnum):
    MANUAL = "MANUAL"
    RSS = "RSS"
    ATOM = "ATOM"
    RSSHUB = "RSSHUB"
    WEB = "WEB"


class SourceHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    PAUSED = "PAUSED"


class SourceFetchStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class SourceFailureKind(StrEnum):
    TIMEOUT = "TIMEOUT"
    HTTP_RETRYABLE = "HTTP_RETRYABLE"
    HTTP_TERMINAL = "HTTP_TERMINAL"
    PARSE = "PARSE"
    EXTRACTION = "EXTRACTION"
    CONFIGURATION = "CONFIGURATION"
    UNKNOWN = "UNKNOWN"
