const capabilities = [
  "React 19 + TypeScript",
  "Vite production build",
  "AppFactory Project Automation",
  "Node.js 24 CI baseline"
];

export default function App() {
  return (
    <main className="app-shell">
      <section className="hero">
        <p className="eyebrow">Generated by Trigenys AppFactory</p>
        <h1>Trigenys Editorial OS</h1>
        <p className="lede">
          Your web application foundation is ready. Keep product-specific domain logic
          separate from this generated shell and evolve the architecture from real requirements.
        </p>
        <div className="capabilities" aria-label="Baseline capabilities">
          {capabilities.map((capability) => (
            <span key={capability}>{capability}</span>
          ))}
        </div>
      </section>
    </main>
  );
}
